name: farmmon_flutter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  cupertino_icons: ^1.0.5
  intl: ^0.17.0
  fl_chart: ^0.62.0
  google_fonts: ^4.0.4
  http: ^0.13.6
  dio: ^5.1.2
  font_awesome_flutter: ^10.4.0
  shared_preferences: ^2.1.1
  path_provider: ^2.0.15
  archive: ^3.3.7
  fluttertoast: ^8.2.2
  foundation: ^0.0.5
  geolocator: ^9.0.2
  flutter_svg: ^2.0.5
  kakao_flutter_sdk_user: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  fonts:
      - family: CustomIcons
        fonts:
         - asset: fonts/CustomIcons.ttf

  assets:
    - assets/json/
    - assets/images/
